package com.itheima.dianshang.dataobject;

import java.math.BigDecimal;

public class CeshiDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ceshi.id
     *
     * @mbg.generated Tue Oct 27 16:09:12 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ceshi.ziduan1
     *
     * @mbg.generated Tue Oct 27 16:09:12 CST 2020
     */
    private BigDecimal ziduan1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ceshi.ziduan2
     *
     * @mbg.generated Tue Oct 27 16:09:12 CST 2020
     */
    private BigDecimal ziduan2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ceshi.id
     *
     * @return the value of ceshi.id
     *
     * @mbg.generated Tue Oct 27 16:09:12 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ceshi.id
     *
     * @param id the value for ceshi.id
     *
     * @mbg.generated Tue Oct 27 16:09:12 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ceshi.ziduan1
     *
     * @return the value of ceshi.ziduan1
     *
     * @mbg.generated Tue Oct 27 16:09:12 CST 2020
     */
    public BigDecimal getZiduan1() {
        return ziduan1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ceshi.ziduan1
     *
     * @param ziduan1 the value for ceshi.ziduan1
     *
     * @mbg.generated Tue Oct 27 16:09:12 CST 2020
     */
    public void setZiduan1(BigDecimal ziduan1) {
        this.ziduan1 = ziduan1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ceshi.ziduan2
     *
     * @return the value of ceshi.ziduan2
     *
     * @mbg.generated Tue Oct 27 16:09:12 CST 2020
     */
    public BigDecimal getZiduan2() {
        return ziduan2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ceshi.ziduan2
     *
     * @param ziduan2 the value for ceshi.ziduan2
     *
     * @mbg.generated Tue Oct 27 16:09:12 CST 2020
     */
    public void setZiduan2(BigDecimal ziduan2) {
        this.ziduan2 = ziduan2;
    }
}