package com.itheima.dianshang.dao;

import com.itheima.dianshang.dataobject.CeshiDO;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface CeshiDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ceshi
     *
     * @mbg.generated Tue Oct 27 16:09:12 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ceshi
     *
     * @mbg.generated Tue Oct 27 16:09:12 CST 2020
     */
    int insert(CeshiDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ceshi
     *
     * @mbg.generated Tue Oct 27 16:09:12 CST 2020
     */
    int insertSelective(CeshiDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ceshi
     *
     * @mbg.generated Tue Oct 27 16:09:12 CST 2020
     */
    CeshiDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ceshi
     *
     * @mbg.generated Tue Oct 27 16:09:12 CST 2020
     */
    int updateByPrimaryKeySelective(CeshiDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ceshi
     *
     * @mbg.generated Tue Oct 27 16:09:12 CST 2020
     */
    int updateByPrimaryKey(CeshiDO record);
}